package fr.tse.fise2.info4.lab10.exercise2;

import java.util.concurrent.BlockingQueue;

/**
 * TODO complete this class as follows:
 * <ol>
 * <li>Constructor takes as parameter the number of sentences to generate and
 * the {@link BlockingQueue} in which to write the sentences</li>
 * <li>When {@link #run()} is called, the producer starts producing sentences in the queue</li>
 * <li>You must keep track of the number of words generated</li>
 * 
 * </ol>
 * 
 * 
 *
 */
public class Producer implements Runnable {

	@Override
	public void run() {

	}

	/**
	 * 
	 * @param words
	 *            the number of words in the sentence
	 * @return the generated sentence
	 */
	public String generateSentence(int words) {
		// Use the lorem ipsum generator
		// Library already in the pom (see maven dependencies)
		// Refer to the documentation : http://loremipsum.sourceforge.net/
		// TODO complete this method
		return null;
	}
	
	/**
	 * 
	 * @return the number of words generated by the producer. If production is not finished throw an {@link IllegalStateException}
	 */
	public int generatedWords(){
		//TODO complete this method
		return -1;
	}

}
